image: "artifactory-gojek.golabs.io:6555/cx-ruby:2.4.1"

stages:
  - build
  - deploy

test:
  stage: build
  script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-client libpq-dev
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rspec

staging:
  stage: deploy
  script:
    - gem install dpl --no-ri --no-rdoc
    - dpl --provider=heroku --app=gojek-twitter-integration --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

production:
  stage: deploy
  script:
    - gem install dpl --no-ri --no-rdoc
    - dpl --provider=heroku --app=gojek-twitter --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
  when: manual
