image: "artifactory-gojek.golabs.io:6555/cx-ruby:2.4.1"

variables:
  POSTGRES_DB: "twitter_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: ""

stages:
  - build
  - deploy

test:
  stage: build
  services:
  - postgres
  script:
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rspec

staging:
  stage: deploy
  script:
    - gem install dpl --no-ri --no-rdoc
    - dpl --provider=heroku --app=gojek-twitter-integration --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

production:
  stage: deploy
  script:
    - gem install dpl --no-ri --no-rdoc
    - dpl --provider=heroku --app=gojek-twitter --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
  when: manual
