default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: twitter_development

test:
  <<: *default
  database: twitter_test
  user: runner
  host: postgres

production:
  <<: *default
  database: twitter_production
